#!/usr/bin/env bash

# Symlinks
ln -s ~/.config/leftwm/Catppuccin/* ~/.config/leftwm/themes/current


# Scriptpath
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# apply theme.ron
leftwm-command "LoadTheme $HOME/.config/leftwm/themes/Catppuccin/theme.ron"


# autostart
$HOME/.config/polybar/launch.sh
xwallpaper --center $HOME/Pictures/Wallpapers/Flatppuccin/flatppuccin.png




