#!/usr/bin/env bash

# Symlinks
#ln -s ~/.config/leftwm/Catppuccin/* ~/.config/leftwm/themes/current


# Scriptpath
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# apply theme.ron
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"


# autostart
/usr/bin/nvidia-settings --load-config-only &
$HOME/.config/polybar/launch.sh &
xwallpaper --maximize $HOME/Pictures/Wallpapers/Catppuccin/silentsea.jpg &
xinput --set-prop 'pointer:''Razer Orochi V2' 'libinput Accel Profile Enabled' 0, 1 &
picom





